# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lead, Kindly Byte
email: n.deepak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Musings on technology
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://deepix.github.io" # the base hostname & protocol for your site
domain_url: "https://ndeepak.com/"
# twitter_username: deepix
github_username:  deepix
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
